version: 0.0
os: windows
files:
  - source: .\index.html           
    destination: c:\test
  - source: .\index2.html           
    destination: c:\test
hooks:
  BeforeInstall:
    - location: \before-install.bat
      timeout: 900
